services:
  - type: web
    name: intuition-market
    env: node
    plan: starter
    buildCommand: bun install && bun run build
    startCommand: bun start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: development
      - key: MULTIVAULT_ADDRESS
        value: '0x63B90A9c109fF8f137916026876171ffeEdEe714'
      - key: PRIVATE_KEY
        sync: false
      - key: PUBLIC_KEY
        sync: false
      - key: ENVIRONMENT
        value: development
      - key: DYNAMIC_API_KEY
        sync: false
      - key: DYNAMIC_PUBLIC_KEY
        sync: false
      - key: DYNAMIC_ENVIRONMENT_ID
        sync: false
      - key: APP_NAME
        sync: false
      - key: APP_DESCRIPTION
        sync: false
      - key: APP_IMAGE
        sync: false
      - key: APP_URL
        sync: false
      - key: NEXT_PUBLIC_MULTIVAULT_ADDRESS
        value: '0x63B90A9c109fF8f137916026876171ffeEdEe714'
      - key: NEXT_PUBLIC_ENVIRONMENT
        value: development
      - key: NEXT_PUBLIC_DYNAMIC_ENVIRONMENT_ID
        sync: false
      - key: NEXT_PUBLIC_APP_NAME
        sync: false
      - key: NEXT_PUBLIC_APP_DESCRIPTION
        sync: false
      - key: NEXT_PUBLIC_APP_IMAGE
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false
